# Generated by Django 5.2.7 on 2025-10-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('unique_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('generated_description', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('image_links', models.JSONField(default=list)),
                ('manufacturer', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('package_dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('combined_text', models.TextField()),
            ],
        ),
    ]
